using Microsoft.Data.SqlClient;
using System.Data;

namespace _45Disconnected
{
    internal class Program
    {
        static void Main(string[] args)
        {

            String conStr = "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=IETDb;Integrated Security=True";

            #region Select query
            //SqlConnection con = new SqlConnection(conStr);

            //SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM Emp", con);

            //da.MissingSchemaAction = MissingSchemaAction.AddWithKey;

            //DataSet ds = new DataSet();

            //da.Fill(ds, "Emp");

            //foreach (DataRow Row in ds.Tables["Emp"].Rows)
            //{
            //    int id = Convert.ToInt32(Row["Id"]);
            //    string name = Row["name"].ToString();
            //    string address = Row["adrr"].ToString();

            //    Console.WriteLine($"Id: {id}, Name: {name}, Address: {address}");
            //}
            #endregion

            #region MyRegion
            SqlConnection con = new SqlConnection(conStr);
            SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM EMP", con);

            da.MissingSchemaAction = MissingSchemaAction.AddWithKey;

            SqlCommandBuilder builder = new SqlCommandBuilder(da);

            DataSet ds = new DataSet();
            da.Fill(ds, "Emp");
            //ds.GetXml()

            Console.WriteLine("Enter Name:");
            string nm = Console.ReadLine();
            Console.WriteLine("Enter Address:");
            string add = Console.ReadLine();

            DataRow newRow = ds.Tables["Emp"].NewRow();
            newRow["name"] = nm;
            newRow["adrr"] = add;

            ds.Tables["Emp"].Rows.Add(newRow);

            da.Update(ds, "Emp");//Insert Query is generated by CommandBuilder
            Console.WriteLine("Record inserted!");



            #endregion




        }
    }
}
